config/routes.rb
Knocta::Application.routes.draw do
  get "page/home"

  get "page/about"

  get "page/articles"

  get "page/blog"

  get "page/contact"

  get "page/log_in"

  get "say/hello"

  get "say/goodbye"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home

    @year = params[:year]
    @month = params[:month]

  end

  def about
  end

  def articles
  end

  def blog
  end

  def contact
  end

  def log_in
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello

  end

  def goodbye

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def calendar(month, year)
    prev_month = link_to"Previous", page_home_path(:month => month.to_i - 1)
    cal_str = "<table border='1>'"
    cal_str += "<tr><td>#{prev_month}</td><td colspan=6>October</td></tr>"
    cal_str += "<tr>"
    cal_str += "<td>&nbsp;</td>"
      6.times do |day|
        cal_str += "<td>#{day + 1}</td>"
      end
    cal_str += "</tr>"
    cal_str += "</table>"
    return cal_str.html_safe
  end

end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Knocta</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "styles", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
    <div class="bg">
        <!--start container-->
        <div id="container">
            <!--start header-->
            <header>
                <!--start logo-->
                <!--<a href="#" id="logo"><img src="images/logo.png" width="180" height="43" alt="logo"/></a>-->
                <h1>Knocta</h1>
                <!--end logo-->
                <!--start menu-->
                <%= render :partial => 'shared/navigation' %>
                <!--end menu-->
                <!--end header-->
            </header>
            <!--start intro-->
            <section id="intro">
                <hgroup>
                    <h1>"Simplicity is the ultimate sophistication"<span>- Leonardo da Vinci</span></h1>
                    <h2>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin.
                        Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</h2>
                </hgroup>
            </section>
            <!--end intro-->
            <!--start holder-->
            <div class="holder_content">
                <section class="group4">
                    <h3>Latest article</h3>
                    <article>
<%= yield %>
                    </article>
                </section>
            </div>
            <!--end holder-->
        </div>
            <!--end container-->
            <!--start footer-->
            <%= render :partial => 'shared/footer' %></div>
        <!--end bg-->
        <!-- Free template distributed by http://freehtml5templates.com -->
</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>
<br />
<%= Time.now %>
<br />

<p><b><%= @month %> <%= @year %> Whatever</b></p>
<br />
<%= calendar(@month, @year) %>

app/views/page/log_in.html.erb
<h1>Page#log_in</h1>
<p>Find me in app/views/page/log_in.html.erb</p>

app/views/say/goodbye.html.erb
<h1>Saying Goodbye</h1>
<h4>Yo goodbye!!!</h4>

app/views/say/hello.html.erb
<h1>Hello Action</h1>
<h4>Saying hello form the Say Controller!!!</h4>

app/views/shared/_footer.html.erb
<footer>
    <div class="container">
        <div id="FooterTwo">Knocta </div>
        <div id="FooterTree"> Knocta Knocta Knocta </div>
    </div>
</footer>
<!--end footer-->

app/views/shared/_navigation.html.erb
<nav>
    <ul>
        <li><%= link_to_unless_current "Home", page_home_path %></li>
        <li><%= link_to_unless_current "About", page_about_path %></li>
        <li><%= link_to_unless_current "Articles", page_articles_path %></li>
        <li><%= link_to_unless_current "Blog", page_blog_path %></li>
        <li><%= link_to_unless_current "Contact", page_contact_path %></li>
        <li><%= link_to_unless_current "Log in!!!", page_log_in_path %></li>
    </ul>
</nav>